### ISSUE TITLE
`getOwner` crashes on Mainnet if the ENS domain name does not exist/has not been registtered

### ISSUE THREAD

**Issue by Magofoco** [ensdomains/ensjs-v3#97] opened 2023-01-05 01:19 UTC
On Mainnet, the function `.getOwner` crashes with an error if the ENS domain name input to the function has not been registered.

Example:

```js
    const NOT_REGISTERED_ENS_DOMAIN = "thisisnotregisteredens.eth"
    const ownerObject = await ENSInstance.getOwner(NOT_REGISTERED_ENS_DOMAIN);
    console.log(ownerObject);
```
crashes with the following error instead of returning `undefined`

```js
/home/x/node_modules/graphql-request/dist/index.js:67
            op = body.call(thisArg, _);
                      ^
ClientError: Type `Domain` has no field `registration`: {"response":{"errors":[{"locations":[{"line":3,"column":5}],"message":"Type `Domain` has no field `registration`"}],"status":200,"headers":{}},"request":{"query":"\n  query GetRegistrant($namehash: String!) {\n    domain(id: $namehash) {\n      registration {\n        registrant {\n          id\n        }\n      }\n    }\n  }\n","variables":{"namehash":"0xd4a5aec5954a3e37fc24f33c3bd145d0e258e521f74a15371e3d3079637047b3"}}}
    at /home/x/node_modules/graphql-request/src/index.ts:498:11
    at step (/home/x/node_modules/graphql-request/dist/index.js:67:23)
    at Object.next (/home/x/node_modules/graphql-request/dist/index.js:48:53)
    at fulfilled (/home/x/node_modules/graphql-request/dist/index.js:39:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  response: {
    errors: [ [Object] ],
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: '\n' +
      '  query GetRegistrant($namehash: String!) {\n' +
      '    domain(id: $namehash) {\n' +
      '      registration {\n' +
      '        registrant {\n' +
      '          id\n' +
      '        }\n' +
      '      }\n' +
      '    }\n' +
      '  }\n',
    variables: {
      namehash: '0xd4a5aec5954a3e37fc24f33c3bd145d0e258e521f74a15371e3d3079637047b3'
    }
  }
}

```

**However**
On Goerli Network, the same function does not crash and returns, correctly, `undefined` since the ens domain "thisisnotregisteredens.eth" is still available to be purchased

**Comment by TateB** [comment] 2023-01-09 01:23
hey, this is because currently the mainnet and goerli ENS subgraphs differ slightly, meaning that sometimes things will break on mainnet for the moment. a fix for this issue at the moment could be to disable subgraph communication entirely by passing a `null` value for `graphURI` in the ENS class constructor.

e.g.
```js
const ENSInstance = new ENS({ graphURI: null })
```

**Comment by Magofoco** [comment] 2023-01-13 00:13
I tried this solution but the error persists

**Comment by Magofoco** [comment] 2023-01-13 00:29
For now, I am solving it with a `try` and `catch`.
I created a standalone function called `getMaybeOwner` that calls `.getOwner()`. If the ens name exists, the functions returns either an object or null (as expected). Else, it enters the `catch` block and returns `null`

```js
const getMaybeOwner = async (ensName: string, ENSInstance: ENS) => {
  try {
    const maybeEnsRegisteredObject = await ENSInstance.getOwner(
      ensName
    );
    return maybeEnsRegisteredObject;
  } catch (e) {
    return null;
  }
};

export default getMaybeOwner;
```

Now, instead of calling `await ENSInstance.getOwner(ensName)` I call `await getMaybeOwner(ensName, ENSInstance);`

**Comment by Magofoco** [comment] 2023-01-19 16:54
@TateB If you want, I can implement the `getMaybeOwner` function

**Comment by Magofoco** [comment] 2023-01-19 16:55
@TateB If you want, I can implement the `getMaybeOwner` function

**Comment by TateB** [comment] 2023-01-19 23:09
a new subgraph is syncing now, will take a few days but once it's done this should work

**Comment by TateB** [comment] 2023-01-24 23:30
@Magofoco hey, this should work now

**Comment by Magofoco** [comment] 2023-01-25 14:25
@TateB Thanks! It seems to work :)

**Comment by Magofoco** [comment] 2023-01-25 14:31
@TateB Hello!
I tried it with a ens domain that does not exist and returns correctly "undefined". HOWEVER, it returns `undefined` also for a ens domain that exists (ex. vitalik.eth)

I am suing: `"@ensdomains/ensjs": "^3.0.0-alpha.42"`

**Comment by TateB** [comment] 2023-01-27 00:42
@Magofoco there were some issues with running the package through nodejs, should be fixed now (version `3.0.0-alpha.43`)

**Comment by Magofoco** [comment] 2023-01-30 18:14
@TateB I am experiencing the same error.  It returns undefined also for a ens domain that exists (ex. vitalik.eth)

**Comment by TateB** [comment] 2023-01-30 21:42
can you provide a gist of your code or something? i can't replicate the issue

**Comment by Magofoco** [comment] 2023-01-31 11:25
@TateB Sure! Here it is

```js
import { ethers } from "ethers";
import * as dotenv from "dotenv";
import { ENS } from "@ensdomains/ensjs";

dotenv.config();

const { INFURA_API_KEY } = process.env;
const INFURA_NODE_MAINNET = `https://mainnet.infura.io/v3/${INFURA_API_KEY}`;

const provider = new ethers.providers.JsonRpcProvider(INFURA_NODE_MAINNET);
const ENSInstance = new ENS();

const POLLING_INTERVAL_MILLISECONDS = 20000;

const main = async () => {
  await ENSInstance.setProvider(provider);

  const polledFunction = async () => {

    const existingEns = await ENSInstance.getOwner("vitalik.eth");
    const nonExistingEns = await ENSInstance.getOwner("jdklasjjjalskdjasl.eth");
    console.log(existingEns); <--- RETURNS WRONGLY UNDEFINED
    console.log(nonExistingEns); <-- RETURNS UNDEFINED
  };

  setInterval(polledFunction, POLLING_INTERVAL_MILLISECONDS);
};

main()
```

**Comment by TateB** [comment] 2023-02-06 22:20
still can't replicate the issue,
do you think you could create a barebones repo for reproducing it?

**Comment by Magofoco** [comment] 2023-02-07 17:08
@TateB 
Take a look here:
https://github.com/Magofoco/ensIssueTest

**Comment by TateB** [comment] 2023-02-08 01:13
a few minor things that got it working for me:
- in `package.json`: add `"type": "module"`
- in `tsconfig.json`:
  - set `module` to `ESNext`
  - set `moduleResolution` to `node`

**Comment by Magofoco** [comment] 2023-02-09 14:45
Thanks @TateB , with your changes the version `3.0.0-alpha.43` work as expected.
Thank you!

(Just for your knowledge, `3.0.0-alpha.39` was working without needing to change the `package.json` and `tsconfig.json`)

**Closed** 2023-02-10 05:40 UTC
